name: On issue open assign to user and move to project

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v1.11.0
        with:
          assignees: AurisTFG
          numOfAssignee: 1

  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: MatchMania Kanban Board
          column: Backlog
          repo-token: ${{ secrets.GITHUB_TOKEN }}
