services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matchmania-api
    environment:
      - MATCHMANIA_ENV=development
    env_file: ./backend/.env.development
    ports:
      - "8080:8080"
    restart: unless-stopped
