// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "AurisTFG",
            "url": "https://github.com/AurisTFG"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Log in",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "Log in details",
                        "name": "loginDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Log out",
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Get current user",
                "tags": [
                    "auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.UserDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh token",
                "tags": [
                    "auth"
                ],
                "summary": "Refresh token",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Sign up",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "Sign up details",
                        "name": "signUpDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.SignupDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/matchmaking/queue/join": {
            "post": {
                "description": "Join matchmaking queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matchmaking"
                ],
                "summary": "Join matchmaking queue",
                "parameters": [
                    {
                        "description": "Join Queue DTO",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.JoinQueueDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/matchmaking/queue/leave": {
            "post": {
                "description": "Leave matchmaking queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matchmaking"
                ],
                "summary": "Leave matchmaking queue",
                "parameters": [
                    {
                        "description": "Leave Queue DTO",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.LeaveQueueDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/matchmaking/queue/status/{teamId}": {
            "get": {
                "description": "Check match status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matchmaking"
                ],
                "summary": "Check match status",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.MatchStatusDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/matchmaking/queue/teams-count/{seasonId}": {
            "get": {
                "description": "Get matchmaking queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matchmaking"
                ],
                "summary": "Get matchmaking queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.QueueTeamsCountDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/seasons": {
            "get": {
                "description": "Get all seasons",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Get all seasons",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.SeasonDto"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Create a season",
                "parameters": [
                    {
                        "description": "Season object that needs to be created",
                        "name": "season",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateSeasonDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}": {
            "get": {
                "description": "Get a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Get a season",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SeasonDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Delete a season",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Update a season",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Season object that needs to be updated",
                        "name": "season",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateSeasonDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams": {
            "get": {
                "description": "Get all teams",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Get all teams",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.TeamDto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Create a team",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team object that needs to be created",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateTeamDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams/{teamId}": {
            "get": {
                "description": "Get a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Get a team",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.TeamDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Delete a team",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Update a team",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team object that needs to be updated",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateTeamDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams/{teamId}/results": {
            "get": {
                "description": "Get all results",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Get all results",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.ResultDto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Create a result",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Result object that needs to be created",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateResultDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams/{teamId}/results/{resultId}": {
            "get": {
                "description": "Get a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Get a result",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Result ID",
                        "name": "resultId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.ResultDto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Delete a result",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Result ID",
                        "name": "resultId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Update a result",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0deecf6a-289b-49a0-8f1b-9bc4185f99df",
                        "description": "Result ID",
                        "name": "resultId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Result object that needs to be updated",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateResultDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/trackmania/oauth/callback": {
            "get": {
                "description": "Handle Trackmania OAuth callback",
                "tags": [
                    "trackmania"
                ],
                "summary": "Handle Trackmania OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "State parameter",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/trackmania/oauth/url": {
            "get": {
                "description": "Start Trackmania OAuth flow",
                "tags": [
                    "trackmania"
                ],
                "summary": "Start Trackmania OAuth flow",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.TrackmaniaOAuthUrlDto"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorDto"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.UserMinimalDto"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Get user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.UserMinimalDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "enums.Role": {
            "type": "string",
            "enum": [
                "admin",
                "moderator",
                "user"
            ],
            "x-enum-varnames": [
                "AdminRole",
                "ModeratorRole",
                "UserRole"
            ]
        },
        "requests.CreateResultDto": {
            "type": "object",
            "required": [
                "endDate",
                "opponentTeamId",
                "startDate"
            ],
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:000Z"
                },
                "opponentScore": {
                    "type": "string",
                    "example": "14"
                },
                "opponentTeamId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "score": {
                    "type": "string",
                    "example": "16"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:000Z"
                }
            }
        },
        "requests.CreateSeasonDto": {
            "type": "object",
            "required": [
                "endDate",
                "name",
                "startDate"
            ],
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:000Z"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Summer 2025"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:000Z"
                }
            }
        },
        "requests.CreateTeamDto": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "BIG Clan"
                }
            }
        },
        "requests.JoinQueueDto": {
            "type": "object",
            "required": [
                "seasonId",
                "teamId"
            ],
            "properties": {
                "seasonId": {
                    "type": "string"
                },
                "teamId": {
                    "type": "string"
                }
            }
        },
        "requests.LeaveQueueDto": {
            "type": "object",
            "required": [
                "seasonId",
                "teamId"
            ],
            "properties": {
                "seasonId": {
                    "type": "string"
                },
                "teamId": {
                    "type": "string"
                }
            }
        },
        "requests.LoginDto": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "email@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "VeryStrongPassword"
                }
            }
        },
        "requests.SignupDto": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "email@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "VeryStrongPassword"
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "john_doe_123"
                }
            }
        },
        "requests.UpdateResultDto": {
            "type": "object",
            "required": [
                "endDate",
                "opponentTeamId",
                "startDate"
            ],
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:000Z"
                },
                "opponentScore": {
                    "type": "string",
                    "example": "14"
                },
                "opponentTeamId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "score": {
                    "type": "string",
                    "example": "16"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:000Z"
                }
            }
        },
        "requests.UpdateSeasonDto": {
            "type": "object",
            "required": [
                "endDate",
                "name",
                "startDate"
            ],
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:000Z"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Summer 2025"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:000Z"
                }
            }
        },
        "requests.UpdateTeamDto": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "BIG Clan"
                }
            }
        },
        "responses.ErrorDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Error message"
                }
            }
        },
        "responses.MatchStatusDto": {
            "type": "object",
            "properties": {
                "isInMatch": {
                    "type": "boolean"
                }
            }
        },
        "responses.QueueTeamsCountDto": {
            "type": "object",
            "properties": {
                "teamsCount": {
                    "type": "integer"
                }
            }
        },
        "responses.ResultDto": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-06-01T00:40:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "opponentScore": {
                    "type": "string",
                    "example": "14"
                },
                "opponentTeam": {
                    "$ref": "#/definitions/teams.TeamMinimalDto"
                },
                "score": {
                    "type": "string",
                    "example": "16"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "team": {
                    "$ref": "#/definitions/teams.TeamMinimalDto"
                },
                "user": {
                    "$ref": "#/definitions/users.UserMinimalDto"
                }
            }
        },
        "responses.SeasonDto": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Summer 2025"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "user": {
                    "$ref": "#/definitions/users.UserMinimalDto"
                }
            }
        },
        "responses.TeamDto": {
            "type": "object",
            "properties": {
                "elo": {
                    "type": "integer",
                    "example": 1200
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "BIG Clan"
                },
                "user": {
                    "$ref": "#/definitions/users.UserMinimalDto"
                }
            }
        },
        "responses.TrackmaniaOAuthUrlDto": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "responses.UserDto": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string",
                    "example": "FR"
                },
                "email": {
                    "type": "string",
                    "example": "email@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "526432ea-822b-4b5b-b1b3-34e8ab453e03"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.Role"
                        }
                    ],
                    "example": "admin"
                },
                "trackmaniaId": {
                    "type": "string",
                    "example": "526432ea-822b-4b5b-b1b3-34e8ab453e03"
                },
                "trackmaniaName": {
                    "type": "string",
                    "example": "JohnDoe"
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trackmanioauth.TrackmaniaOAuthTracksDto"
                    }
                },
                "username": {
                    "type": "string",
                    "example": "john_doe_123"
                }
            }
        },
        "responses.UserMinimalDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "526432ea-822b-4b5b-b1b3-34e8ab453e03"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe_123"
                }
            }
        },
        "teams.TeamMinimalDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "BIG Clan"
                }
            }
        },
        "trackmanioauth.TrackmaniaOAuthTracksDto": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "users.UserMinimalDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "526432ea-822b-4b5b-b1b3-34e8ab453e03"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe_123"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "MatchMania API",
	Description:      "Documentation for MatchMania API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
