// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/seasons": {
            "get": {
                "description": "Get all seasons",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Get all seasons",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SeasonsResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Create a season",
                "parameters": [
                    {
                        "description": "Season object that needs to be created",
                        "name": "season",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateSeasonDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SeasonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.UnprocessableEntityResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}": {
            "get": {
                "description": "Get a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Get a season",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SeasonResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Update a season",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Season object that needs to be updated",
                        "name": "season",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateSeasonDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SeasonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a season",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seasons"
                ],
                "summary": "Delete a season",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams": {
            "get": {
                "description": "Get all teams",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Get all teams",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TeamsResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Create a team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team object that needs to be created",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTeamDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.UnprocessableEntityResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams/{teamId}": {
            "get": {
                "description": "Get a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Get a team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TeamResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Update a team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team object that needs to be updated",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateTeamDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Delete a team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams/{teamId}/results": {
            "get": {
                "description": "Get all results",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Get all results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResultsResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Create a result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Result object that needs to be created",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateResultDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.UnprocessableEntityResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            }
        },
        "/seasons/{seasonId}/teams/{teamId}/results/{resultId}": {
            "get": {
                "description": "Get a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Get a result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Result ID",
                        "name": "resultId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResultResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Update a result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Result ID",
                        "name": "resultId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Result object that needs to be updated",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateResultDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Delete a result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Season ID",
                        "name": "seasonId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Result ID",
                        "name": "resultId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.NotFoundResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.BadGatewayResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BadGatewayResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Unable to communicate with the database"
                }
            }
        },
        "models.BadRequestResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "JSON parsing error"
                }
            }
        },
        "models.CreateResultDto": {
            "type": "object",
            "required": [
                "matchEndDate",
                "matchStartDate",
                "opponentTeamId"
            ],
            "properties": {
                "matchEndDate": {
                    "type": "string",
                    "example": "2025-06-01T00:40:00Z"
                },
                "matchStartDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "opponentScore": {
                    "type": "integer",
                    "example": 14
                },
                "opponentTeamId": {
                    "type": "integer",
                    "example": 7
                },
                "score": {
                    "type": "integer",
                    "example": 16
                }
            }
        },
        "models.CreateSeasonDto": {
            "type": "object",
            "required": [
                "endDate",
                "name",
                "startDate"
            ],
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:00Z"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Summer 2025"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                }
            }
        },
        "models.CreateTeamDto": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "BIG Clan"
                }
            }
        },
        "models.NotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Resource was not found"
                }
            }
        },
        "models.ResultDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 7
                },
                "matchEndDate": {
                    "type": "string",
                    "example": "2025-06-01T00:40:00Z"
                },
                "matchStartDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "opponentScore": {
                    "type": "integer",
                    "example": 14
                },
                "opponentTeam": {
                    "type": "integer",
                    "example": 7
                },
                "score": {
                    "type": "integer",
                    "example": 16
                },
                "team": {
                    "type": "integer",
                    "example": 6
                }
            }
        },
        "models.ResultResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/models.ResultDto"
                }
            }
        },
        "models.ResultsResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ResultDto"
                    }
                }
            }
        },
        "models.SeasonDto": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 5
                },
                "name": {
                    "type": "string",
                    "example": "Summer 2025"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                }
            }
        },
        "models.SeasonResponse": {
            "type": "object",
            "properties": {
                "season": {
                    "$ref": "#/definitions/models.SeasonDto"
                }
            }
        },
        "models.SeasonsResponse": {
            "type": "object",
            "properties": {
                "seasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SeasonDto"
                    }
                }
            }
        },
        "models.TeamDto": {
            "type": "object",
            "properties": {
                "elo": {
                    "type": "integer",
                    "example": 1200
                },
                "id": {
                    "type": "integer",
                    "example": 6
                },
                "name": {
                    "type": "string",
                    "example": "BIG Clan"
                }
            }
        },
        "models.TeamResponse": {
            "type": "object",
            "properties": {
                "team": {
                    "$ref": "#/definitions/models.TeamDto"
                }
            }
        },
        "models.TeamsResponse": {
            "type": "object",
            "properties": {
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TeamDto"
                    }
                }
            }
        },
        "models.UnprocessableEntityResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Validation error"
                }
            }
        },
        "models.UpdateResultDto": {
            "type": "object",
            "required": [
                "matchEndDate",
                "matchStartDate"
            ],
            "properties": {
                "matchEndDate": {
                    "type": "string",
                    "example": "2025-06-01T00:40:00Z"
                },
                "matchStartDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "opponentScore": {
                    "type": "integer",
                    "example": 14
                },
                "score": {
                    "type": "integer",
                    "example": 16
                }
            }
        },
        "models.UpdateSeasonDto": {
            "type": "object",
            "required": [
                "endDate",
                "name",
                "startDate"
            ],
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-08-31T00:00:00Z"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Summer 2025"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                }
            }
        },
        "models.UpdateTeamDto": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "BIG Clan"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "MatchMania API",
	Description:      "This is an API for managing matchmaking seasons, teams, and results",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
