name: On Branch Create move issue to "In Progress" column in Project

on: create

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: MatchMania Kanban Board
          column: In Progress
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
