name: On Issue Open assign issue to user

on:
  issues:
    types:
      - opened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to user
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: "auristfg"
